### PR TITLE
Fix accessing UIViewManager configs

### LINKED ISSUE #437: new warning while upgrading to RN 0.58
after upgrading to react native 0.58 (from 0.57) i've started to see a this warning:
Accessing view manager configs directly off UIManager via UIManager['LottieAnimationView'] is no longer supported. Use UIManager.getViewManagerConfig('LottieAnimationView') instead

### PR DESCRIPTION
**Pull request by andrewtremblay**
# Summary

This PR should remove the warning regarding UIViewManager accessing  LottieAnimationView directly. 
See the source comments for more information:
https://github.com/facebook/react-native/blob/fc94ade11c09bc5ed027f7ebd58341d851d4c3fb/Libraries/ReactNative/UIManagerProperties.js#L15

Closes #437

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅  |
| Android |    ✅   |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I mentioned this change in `CHANGELOG.md`

### CODE REVIEW

File: src/js/LottieView.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ class LottieView extends React.Component {
       android: () =>
         UIManager.dispatchViewManagerCommand(
           handle,
-          UIManager.LottieAnimationView.Commands[name],
+          UIManager.getViewManagerConfig('LottieAnimationView').Commands[name],
```
Comment (XeroX) [inline src/js/LottieView.js]: Would this break support of RN < 0.58 since `getViewManagerConfig` doesn't exist in older versions or am I missing something?

Comment (ahanriat) [reply src/js/LottieView.js]: @XeroX Agree,  something like [this](https://github.com/lelandrichardson/react-native-safe-module/pull/6/files#diff-b3efefcfc3c27304dfc5617d511ce810R21) would be helpful

**Comment by cspicuzza** [comment]
Thank you for your hard work addressing these config fixes.   How soon can we expect a merge?

File: src/js/LottieView.js (hunk 1 above)
Comment (emilioicai) [reply src/js/LottieView.js]: @andrewtremblay can you create a fix for this and ping me once it's ready?

Comment (andrewtremblay-pear) [reply src/js/LottieView.js]: @emilioicai: Just pushed a commit that should address the backwards compatibility issues.

Thanks everyone for your patience!

Comment (andrewtremblay) [reply src/js/LottieView.js]: @emilioicai: Just pushed a commit that should address the backwards compatibility issues.

Thanks everyone for your patience!

**Comment by emilioicai** [comment]
thanks @andrewtremblay !
